// <auto-generated />
using HAS01.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAS01.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325130525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAS01.API.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TicketPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventName = "Tech Workshop",
                            Location = "Online",
                            TicketPrice = 50f
                        },
                        new
                        {
                            Id = 2,
                            EventName = "Music Festival",
                            Location = "Cape Town",
                            TicketPrice = 150f
                        },
                        new
                        {
                            Id = 3,
                            EventName = "Art Exhibition",
                            Location = "Johannesburg",
                            TicketPrice = 75f
                        },
                        new
                        {
                            Id = 4,
                            EventName = "Startup Summit",
                            Location = "Durban",
                            TicketPrice = 100f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
